server:
  host: 127.0.0.1
  port: 8080

logger:
  level: "DEBUG"

storage:
  storageType: memory
  #  storageType: sql
  database:
    host: 127.0.0.1
    port: 5432
    database: postgres
    username: postgres
    password: pas